// Export selected default bags
export const defaultTables = [
  {
    id: 1,
    attributes: [
      'Shrimp',
      'Crackers',
      'Beer',
      'Miso Soup',
      'Cookies of Luck',
      'Pomegranate',
      'Fork of Luck',
      'Green Beans of Despair',
    ],
  },
  {
    id: 69,
    attributes: [
      '"Homemade Dope" Meatloaf of Luck +1',
      'Granola',
      'Wine',
      'Goulash of the King',
      'Flan',
      'Kumquat of Mystery',
      'Spoon',
      'Hard Bread',
    ],
  },
  {
    id: 420,
    attributes: [
      'Stuffed Peppers',
      'Chips',
      'Beer of Stupidity',
      'Potato Leek Soup',
      'Ice Cream',
      'Kumquat',
      'Spoon',
      '"Suspiciously Citrusy" Mac and Cheese of Pestilence',
    ],
  },
  {
    id: 6969,
    attributes: [
      'Pizza',
      'Popcorn',
      'Milkshake',
      'Lobster Biqsue',
      'Eclair',
      'Pineapple',
      'Fork',
      'Mashed Potatoes',
    ],
  },
  {
    id: 1234,
    attributes: [
      'Omelet',
      'Jerky',
      'Tea',
      'Chicken Noodle Soup',
      '"Satoshi\'s Tangy" Creme Brulee of Mystery',
      'Mandarin',
      'Fork',
      'Green Beans of Stealth',
    ],
  },
  {
    id: 1337,
    attributes: [
      'Ramen',
      'Crackers',
      'Water of Doom',
      'Miso',
      'Doughnut',
      'Pomegranate of the King',
      'Spoon of Confusion',
      'Mashed Potatoes of Glory',
    ],
  },
  {
    id: 66,
    attributes: [
      'Ramen of Glory',
      'Almonds',
      'Soju',
      'Tomato Soup',
      'Sorbet',
      'Figs',
      'Spoon of Doom',
      'Mashed Potatoes',
    ],
  },
];
